name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          BUILD_SCRIPT: npm install && vuepress build src
          CNAME: blog.qq-agency.ru
          COMMIT_EMAIL: sergey@php.net
          COMMIT_NAME: Sergey Panteleev