name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: get_file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ' '
      - name: Run spellchecker
        run: npx yaspeller ${{ steps.get_file_changes.outputs.files }}

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: spellcheck
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Yarn
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: src/.vuepress/dist
          BUILD_SCRIPT: yarn run build
          REPOSITORY_NAME: qq-agency/blog.qq-agency.ru
          CNAME: blog.qq-agency.ru
          COMMIT_EMAIL: git@qq-agency.ru
          COMMIT_NAME: QQ